package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Heroe generated by hbm2java
 */
@Entity
@Table(name = "Heroe")
public class Heroe implements java.io.Serializable {

	private Integer idHeroe;
	private int idUser;
	private String nombreHeroe;
	private String sexo;
	private String raza;
	private int nivelHeroe;
	private int oro;
	private int vidaMax;
	private int vidaActual;
	private int manaMax;
	private int manaActual;
	private int staminaMax;
	private float experienciaHeroe;
	private float minutosJugados;
	private int x;
	private int y;
	private int z;

	public Heroe() {
	}

	public Heroe(int idUser, String nombreHeroe, String raza, int nivelHeroe, int oro, int vidaMax, int vidaActual,
			int manaMax, int manaActual, int staminaMax, float experienciaHeroe, float minutosJugados, int x, int y,
			int z) {
		this.idUser = idUser;
		this.nombreHeroe = nombreHeroe;
		this.raza = raza;
		this.nivelHeroe = nivelHeroe;
		this.oro = oro;
		this.vidaMax = vidaMax;
		this.vidaActual = vidaActual;
		this.manaMax = manaMax;
		this.manaActual = manaActual;
		this.staminaMax = staminaMax;
		this.experienciaHeroe = experienciaHeroe;
		this.minutosJugados = minutosJugados;
		this.x = x;
		this.y = y;
		this.z = z;
	}

	public Heroe(int idUser, String nombreHeroe, String sexo, String raza, int nivelHeroe, int oro, int vidaMax,
			int vidaActual, int manaMax, int manaActual, int staminaMax, float experienciaHeroe, float minutosJugados,
			int x, int y, int z) {
		this.idUser = idUser;
		this.nombreHeroe = nombreHeroe;
		this.sexo = sexo;
		this.raza = raza;
		this.nivelHeroe = nivelHeroe;
		this.oro = oro;
		this.vidaMax = vidaMax;
		this.vidaActual = vidaActual;
		this.manaMax = manaMax;
		this.manaActual = manaActual;
		this.staminaMax = staminaMax;
		this.experienciaHeroe = experienciaHeroe;
		this.minutosJugados = minutosJugados;
		this.x = x;
		this.y = y;
		this.z = z;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_heroe", unique = true, nullable = false)
	public Integer getIdHeroe() {
		return this.idHeroe;
	}

	public void setIdHeroe(Integer idHeroe) {
		this.idHeroe = idHeroe;
	}

	@Column(name = "Id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "Nombre_heroe", nullable = false, length = 30)
	public String getNombreHeroe() {
		return this.nombreHeroe;
	}

	public void setNombreHeroe(String nombreHeroe) {
		this.nombreHeroe = nombreHeroe;
	}

	@Column(name = "Sexo", length = 50)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "Raza", nullable = false, length = 20)
	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	@Column(name = "Nivel_heroe", nullable = false)
	public int getNivelHeroe() {
		return this.nivelHeroe;
	}

	public void setNivelHeroe(int nivelHeroe) {
		this.nivelHeroe = nivelHeroe;
	}

	@Column(name = "Oro", nullable = false)
	public int getOro() {
		return this.oro;
	}

	public void setOro(int oro) {
		this.oro = oro;
	}

	@Column(name = "Vida_max", nullable = false)
	public int getVidaMax() {
		return this.vidaMax;
	}

	public void setVidaMax(int vidaMax) {
		this.vidaMax = vidaMax;
	}

	@Column(name = "Vida_actual", nullable = false)
	public int getVidaActual() {
		return this.vidaActual;
	}

	public void setVidaActual(int vidaActual) {
		this.vidaActual = vidaActual;
	}

	@Column(name = "Mana_max", nullable = false)
	public int getManaMax() {
		return this.manaMax;
	}

	public void setManaMax(int manaMax) {
		this.manaMax = manaMax;
	}

	@Column(name = "Mana_actual", nullable = false)
	public int getManaActual() {
		return this.manaActual;
	}

	public void setManaActual(int manaActual) {
		this.manaActual = manaActual;
	}

	@Column(name = "Stamina_max", nullable = false)
	public int getStaminaMax() {
		return this.staminaMax;
	}

	public void setStaminaMax(int staminaMax) {
		this.staminaMax = staminaMax;
	}

	@Column(name = "Experiencia_heroe", nullable = false, precision = 12, scale = 0)
	public float getExperienciaHeroe() {
		return this.experienciaHeroe;
	}

	public void setExperienciaHeroe(float experienciaHeroe) {
		this.experienciaHeroe = experienciaHeroe;
	}

	@Column(name = "Minutos_jugados", nullable = false, precision = 12, scale = 0)
	public float getMinutosJugados() {
		return this.minutosJugados;
	}

	public void setMinutosJugados(float minutosJugados) {
		this.minutosJugados = minutosJugados;
	}

	@Column(name = "X", nullable = false)
	public int getX() {
		return this.x;
	}

	public void setX(int x) {
		this.x = x;
	}

	@Column(name = "Y", nullable = false)
	public int getY() {
		return this.y;
	}

	public void setY(int y) {
		this.y = y;
	}

	@Column(name = "Z", nullable = false)
	public int getZ() {
		return this.z;
	}

	public void setZ(int z) {
		this.z = z;
	}

}
