package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MisionesHeroe generated by hbm2java
 */
@Entity
@Table(name = "Misiones_heroe")
public class MisionesHeroe implements java.io.Serializable {

	private Integer idMisionesHeroe;
	private int idHeroe;
	private int idMision;
	private boolean misionAceptada;
	private boolean misionCompletada;

	public MisionesHeroe() {
	}

	public MisionesHeroe(int idHeroe, int idMision, boolean misionAceptada, boolean misionCompletada) {
		this.idHeroe = idHeroe;
		this.idMision = idMision;
		this.misionAceptada = misionAceptada;
		this.misionCompletada = misionCompletada;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_misiones_heroe", unique = true, nullable = false)
	public Integer getIdMisionesHeroe() {
		return this.idMisionesHeroe;
	}

	public void setIdMisionesHeroe(Integer idMisionesHeroe) {
		this.idMisionesHeroe = idMisionesHeroe;
	}

	@Column(name = "Id_heroe", nullable = false)
	public int getIdHeroe() {
		return this.idHeroe;
	}

	public void setIdHeroe(int idHeroe) {
		this.idHeroe = idHeroe;
	}

	@Column(name = "Id_mision", nullable = false)
	public int getIdMision() {
		return this.idMision;
	}

	public void setIdMision(int idMision) {
		this.idMision = idMision;
	}

	@Column(name = "Mision_aceptada", nullable = false)
	public boolean isMisionAceptada() {
		return this.misionAceptada;
	}

	public void setMisionAceptada(boolean misionAceptada) {
		this.misionAceptada = misionAceptada;
	}

	@Column(name = "Mision_completada", nullable = false)
	public boolean isMisionCompletada() {
		return this.misionCompletada;
	}

	public void setMisionCompletada(boolean misionCompletada) {
		this.misionCompletada = misionCompletada;
	}

}
