package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Misiones generated by hbm2java
 */
@Entity
@Table(name = "Misiones")
public class Misiones implements java.io.Serializable {

	private Integer idMision;
	private String nombreMision;
	private String descripcionMision;
	private boolean eliminarEnemigos;
	private boolean buscarObjetos;
	private boolean interaccionNpc;
	private int nivelRequisito;
	private int premision;
	private String autor;
	private String mecanica;
	private int cantidadPreguntas;
	private String x;
	private String y;
	private String z;
	private String disparador;

	public Misiones() {
	}

	public Misiones(String nombreMision, String descripcionMision, boolean eliminarEnemigos, boolean buscarObjetos,
			boolean interaccionNpc, int nivelRequisito, int premision, String autor, String mecanica,
			int cantidadPreguntas, String x, String y, String z, String disparador) {
		this.nombreMision = nombreMision;
		this.descripcionMision = descripcionMision;
		this.eliminarEnemigos = eliminarEnemigos;
		this.buscarObjetos = buscarObjetos;
		this.interaccionNpc = interaccionNpc;
		this.nivelRequisito = nivelRequisito;
		this.premision = premision;
		this.autor = autor;
		this.mecanica = mecanica;
		this.cantidadPreguntas = cantidadPreguntas;
		this.x = x;
		this.y = y;
		this.z = z;
		this.disparador = disparador;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_mision", unique = true, nullable = false)
	public Integer getIdMision() {
		return this.idMision;
	}

	public void setIdMision(Integer idMision) {
		this.idMision = idMision;
	}

	@Column(name = "Nombre_mision", nullable = false, length = 80)
	public String getNombreMision() {
		return this.nombreMision;
	}

	public void setNombreMision(String nombreMision) {
		this.nombreMision = nombreMision;
	}

	@Column(name = "Descripcion_mision", nullable = false, length = 300)
	public String getDescripcionMision() {
		return this.descripcionMision;
	}

	public void setDescripcionMision(String descripcionMision) {
		this.descripcionMision = descripcionMision;
	}

	@Column(name = "Eliminar_enemigos", nullable = false)
	public boolean isEliminarEnemigos() {
		return this.eliminarEnemigos;
	}

	public void setEliminarEnemigos(boolean eliminarEnemigos) {
		this.eliminarEnemigos = eliminarEnemigos;
	}

	@Column(name = "Buscar_objetos", nullable = false)
	public boolean isBuscarObjetos() {
		return this.buscarObjetos;
	}

	public void setBuscarObjetos(boolean buscarObjetos) {
		this.buscarObjetos = buscarObjetos;
	}

	@Column(name = "Interaccion_npc", nullable = false)
	public boolean isInteraccionNpc() {
		return this.interaccionNpc;
	}

	public void setInteraccionNpc(boolean interaccionNpc) {
		this.interaccionNpc = interaccionNpc;
	}

	@Column(name = "Nivel_requisito", nullable = false)
	public int getNivelRequisito() {
		return this.nivelRequisito;
	}

	public void setNivelRequisito(int nivelRequisito) {
		this.nivelRequisito = nivelRequisito;
	}

	@Column(name = "Premision", nullable = false)
	public int getPremision() {
		return this.premision;
	}

	public void setPremision(int premision) {
		this.premision = premision;
	}

	@Column(name = "Autor", nullable = false, length = 80)
	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Column(name = "Mecanica", nullable = false, length = 80)
	public String getMecanica() {
		return this.mecanica;
	}

	public void setMecanica(String mecanica) {
		this.mecanica = mecanica;
	}

	@Column(name = "CantidadPreguntas", nullable = false)
	public int getCantidadPreguntas() {
		return this.cantidadPreguntas;
	}

	public void setCantidadPreguntas(int cantidadPreguntas) {
		this.cantidadPreguntas = cantidadPreguntas;
	}

	@Column(name = "x", nullable = false, length = 100)
	public String getX() {
		return this.x;
	}

	public void setX(String x) {
		this.x = x;
	}

	@Column(name = "y", nullable = false, length = 100)
	public String getY() {
		return this.y;
	}

	public void setY(String y) {
		this.y = y;
	}

	@Column(name = "z", nullable = false, length = 100)
	public String getZ() {
		return this.z;
	}

	public void setZ(String z) {
		this.z = z;
	}

	@Column(name = "Disparador", nullable = false)
	public String getDisparador() {
		return this.disparador;
	}

	public void setDisparador(String disparador) {
		this.disparador = disparador;
	}

}
