package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PreguntaHeroeId generated by hbm2java
 */
@Embeddable
public class PreguntaHeroeId implements java.io.Serializable {

	private int idMision;
	private int idHeroe;
	private int idPregunta;
	private int estado;

	public PreguntaHeroeId() {
	}

	public PreguntaHeroeId(int idMision, int idHeroe, int idPregunta, int estado) {
		this.idMision = idMision;
		this.idHeroe = idHeroe;
		this.idPregunta = idPregunta;
		this.estado = estado;
	}

	@Column(name = "Id_Mision", nullable = false)
	public int getIdMision() {
		return this.idMision;
	}

	public void setIdMision(int idMision) {
		this.idMision = idMision;
	}

	@Column(name = "Id_heroe", nullable = false)
	public int getIdHeroe() {
		return this.idHeroe;
	}

	public void setIdHeroe(int idHeroe) {
		this.idHeroe = idHeroe;
	}

	@Column(name = "Id_pregunta", nullable = false)
	public int getIdPregunta() {
		return this.idPregunta;
	}

	public void setIdPregunta(int idPregunta) {
		this.idPregunta = idPregunta;
	}

	@Column(name = "Estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreguntaHeroeId))
			return false;
		PreguntaHeroeId castOther = (PreguntaHeroeId) other;

		return (this.getIdMision() == castOther.getIdMision()) && (this.getIdHeroe() == castOther.getIdHeroe())
				&& (this.getIdPregunta() == castOther.getIdPregunta()) && (this.getEstado() == castOther.getEstado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMision();
		result = 37 * result + this.getIdHeroe();
		result = 37 * result + this.getIdPregunta();
		result = 37 * result + this.getEstado();
		return result;
	}

}
