package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PreguntaHeroe generated by hbm2java
 */
@Entity
@Table(name = "Pregunta_heroe")
public class PreguntaHeroe implements java.io.Serializable {

	private PreguntaHeroeId id;

	public PreguntaHeroe() {
	}

	public PreguntaHeroe(PreguntaHeroeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMision", column = @Column(name = "Id_Mision", nullable = false)),
			@AttributeOverride(name = "idHeroe", column = @Column(name = "Id_heroe", nullable = false)),
			@AttributeOverride(name = "idPregunta", column = @Column(name = "Id_pregunta", nullable = false)),
			@AttributeOverride(name = "estado", column = @Column(name = "Estado", nullable = false)) })
	public PreguntaHeroeId getId() {
		return this.id;
	}

	public void setId(PreguntaHeroeId id) {
		this.id = id;
	}

}
