package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RespuestaHtpHeroe generated by hbm2java
 */
@Entity
@Table(name = "Respuesta_htp_Heroe")
public class RespuestaHtpHeroe implements java.io.Serializable {

	private RespuestaHtpHeroeId id;

	public RespuestaHtpHeroe() {
	}

	public RespuestaHtpHeroe(RespuestaHtpHeroeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idRespuesta", column = @Column(name = "Id_Respuesta", nullable = false)),
			@AttributeOverride(name = "idHeroe", column = @Column(name = "Id_Heroe", nullable = false)),
			@AttributeOverride(name = "idPregunta", column = @Column(name = "Id_Pregunta", nullable = false)),
			@AttributeOverride(name = "respuesta", column = @Column(name = "Respuesta", nullable = false)) })
	public RespuestaHtpHeroeId getId() {
		return this.id;
	}

	public void setId(RespuestaHtpHeroeId id) {
		this.id = id;
	}

}
