package com.pacto.web.model;
// Generated 16/11/2018 12:49:47 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RespuestaHtp generated by hbm2java
 */
@Entity
@Table(name = "Respuesta_htp")
public class RespuestaHtp implements java.io.Serializable {

	private Integer idRespuesta;
	private int idPregunta;
	private String respuesta;
	private int idObjeto;

	public RespuestaHtp() {
	}

	public RespuestaHtp(int idPregunta, String respuesta, int idObjeto) {
		this.idPregunta = idPregunta;
		this.respuesta = respuesta;
		this.idObjeto = idObjeto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_respuesta", unique = true, nullable = false)
	public Integer getIdRespuesta() {
		return this.idRespuesta;
	}

	public void setIdRespuesta(Integer idRespuesta) {
		this.idRespuesta = idRespuesta;
	}

	@Column(name = "Id_Pregunta", nullable = false)
	public int getIdPregunta() {
		return this.idPregunta;
	}

	public void setIdPregunta(int idPregunta) {
		this.idPregunta = idPregunta;
	}

	@Column(name = "Respuesta", nullable = false, length = 300)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Column(name = "Id_Objeto", nullable = false)
	public int getIdObjeto() {
		return this.idObjeto;
	}

	public void setIdObjeto(int idObjeto) {
		this.idObjeto = idObjeto;
	}

}
